name: Deploy

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Print Node.js version
        run: node -v

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
