name: Deploy

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: ✅ Test job completed successfully
        run: echo "✅ Test phase completed successfully"

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Print Node.js version
        run: node -v

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build Project
        run: npm run build

      - name: ✅ Deployment Successful
        run: echo "🚀 Deployment completed successfully"
